baseURL = "https://rdv-speakers.fr/"
languageCode = "fr-fr"
title = "Les Rendez-vous des Speakers"
theme = "rdvspeakers-theme-hugo"

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-XXXXXXXX-X"

[params]
    title = "Les Rendez-vous des Speakers"
    description = "*Les Rendez-vous des Speakers* is a series of technical conferences, meetups, workshops and other event for developers, organized by the *Les Rendez-vous des Speakers* crew."
    images = ["images/social-share.jpg"]
    email = "rentreespeakers@gmail.com"
    keywords = "event, conference, speakers, programming, developers"
    copyright = "We ❤️️ speakers"
    subscriptionUrl = ""
    sponsorshipUrl=""
    appleTouchIcon = "apple-touch-icon.png"
    favicon48 = "favicon-48x48.png"
    favicon32 = "favicon-32x32.png"
    favicon16 = "favicon-16x16.png"
    manifest = "manifest.json"
    safariPinnedTab = "safari-pinned-tab.svg"
    themeColor = "#4d4d4d"
    env="production"

[params.currentEvent]
    url="mardi-gras-2021/"
    name="Le Mardi-gras des Speakers"    
    message="Our next event will be:"

[params.logos]
    jumbo = "images/logos/logo_mardi-gras-2021.png"
    header = "images/logos/logo_color_text.png"
    footer = "images/logos/logo_gray_text.png"



[params.footer]

    credits = [
        "Theme based on <a href='https://github.com/GDGToulouse/'>GDG Toulouse</a>'s <a href='https://github.com/GDGToulouse/devfest-theme-hugo'>DevFest Theme Hugo</a>",
        "Logos and graphic identity by <a href='https://twitter.com/lostinbrittany'>Horacio Gonzalez</a>",
    ]


[params.partnerCategories]
    platinium = "Sponsors"
    gold = "Gold"
    silver = "Silver"
    startup = "Startup"
    support = "Partners"
    communautes = "Community"


[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[languages.fr]
    weight = 2
    languageName = "fr"

[languages.fr.params]
    description = "*Les Rendez-vous des Speakers* est une série de conférences techniques, de rencontres, d'ateliers et autres événements pour les développeurs."

[languages.fr.params.currentEvent] 
    url="mardi-gras-2021/"
    name="Le Mardi-gras des Speakers"  
    message="Notre prochain événement sera :"

[languages.fr.params.partnerCategories]
        platinium = "Sponsors"
        gold = "Gold"
        silver = "Silver"
        startup = "Startup"
        support = "Soutien"
        communautes = "Community"

[taxonomies]
  tag = "tags"

#...    
